[package]
name = "multicoin"
version = "0.0.1"
edition = "2024"

[addresses]
multicoin = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[environments]
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"
testnet_wip = "4c78adac"
